INSERT INTO LIST (PATIENT_ID, LIST_NAME) VALUES (100, 'Dennis Heart Surgery');

INSERT INTO SECTION (LIST_ID, SECTION_NAME) VALUES ((SELECT LIST_ID FROM LIST WHERE PATIENT_ID = 100), 'Surgeons');
INSERT INTO SECTION (LIST_ID, SECTION_NAME) VALUES ((SELECT LIST_ID FROM LIST WHERE PATIENT_ID = 100), 'Ward Sister');
INSERT INTO SECTION (LIST_ID, SECTION_NAME) VALUES ((SELECT LIST_ID FROM LIST WHERE PATIENT_ID = 100), 'Scrub Team');

INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Surgeons'), 'Pt seen, consented and marked', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Surgeons'), 'XR booked if needed', FALSE);

INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Ward Sister'), 'Pt arrived', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Ward Sister'), 'Pt ready (gowned / admitted)', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Ward Sister'), 'Pre med given if needed', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Ward Sister'), 'Pregnancy test if needed', FALSE);

INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Scrub Team'), 'XR contacted if needed', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Scrub Team'), 'Theatre ready', TRUE);
INSERT INTO TASK (SECTION_ID, TITLE, REQUIRED) VALUES ((SELECT SECTION_ID FROM SECTION A JOIN LIST B ON B.LIST_ID = A.LIST_ID WHERE B.PATIENT_ID = 100 AND A.SECTION_NAME = 'Scrub Team'), 'Rep contacted if needed', FALSE);





