CREATE TABLE TASK (
    TASK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SECTION_ID BIGINT NOT NULL,
    TITLE VARCHAR(200),
    REQUIRED BOOLEAN,
    STATUS VARCHAR(32) DEFAULT 'New'
);

CREATE TABLE SECTION (
    SECTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LIST_ID BIGINT NOT NULL,
    USER_ID VARCHAR(64),
    SECTION_NAME VARCHAR(200),
    STATUS VARCHAR(32) DEFAULT 'New'
);

CREATE TABLE LIST (
    LIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PATIENT_ID BIGINT NOT NULL,
    LIST_NAME VARCHAR(200),
    STATUS VARCHAR(32) DEFAULT 'New'
);

CREATE TABLE HISTORY (
    ENTRY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ENTRY_DATE DATETIME,
    TASK_ID BIGINT,
    USER_ID VARCHAR(64),
    COMMENTS VARCHAR(200)
);


ALTER TABLE SECTION ADD FOREIGN KEY (LIST_ID) REFERENCES LIST(LIST_ID);
ALTER TABLE TASK ADD FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID);
CREATE INDEX IDX_TASK_SECT_ ON TASK(SECTION_ID);
CREATE INDEX IDX_SECT_LIST_ ON SECTION(LIST_ID, STATUS);
CREATE INDEX IDX_HIST_DATE_ ON HISTORY(ENTRY_DATE);

CREATE SEQUENCE HISTORY_SEQUENCE_ID START WITH (select max(ENTRY_ID) + 1 from HISTORY);
